export const LOAD_ITEM_LIST = "LOAD_ITEM_LIST"
export const CHECK_USER_DATA = "CHECK_USER_DATA"
export const SAVE_NEW_USER = "SAVE_NEW_USER"
export const START = "_START"
export const SUCCESS = "_SUCCESS"
export const FAIL = "_FAIL"
